#!/usr/bin/env python3
"""
Inspect reference data files generated by extract_reference.py

Displays shapes, dtypes, and statistics for all arrays in .npz files.
Useful for debugging and verification.

Usage:
    python scripts/inspect_reference.py reference_data/prompt1/reference.npz
"""

import argparse
from pathlib import Path

import numpy as np


def format_size(num_bytes: int) -> str:
    """Format byte size in human-readable format."""
    for unit in ["B", "KB", "MB", "GB"]:
        if num_bytes < 1024.0:
            return f"{num_bytes:.2f} {unit}"
        num_bytes /= 1024.0
    return f"{num_bytes:.2f} TB"


def inspect_array(name: str, array: np.ndarray):
    """Print detailed statistics for a single array."""
    print(f"\n{name}")
    print(f"  Shape: {array.shape}")
    print(f"  DType: {array.dtype}")
    print(f"  Size: {format_size(array.nbytes)}")

    # Statistics for numeric arrays
    if np.issubdtype(array.dtype, np.number):
        print(f"  Min: {array.min():.6e}")
        print(f"  Max: {array.max():.6e}")
        print(f"  Mean: {array.mean():.6e}")
        print(f"  Std: {array.std():.6e}")

        # Check for NaN/Inf
        if np.issubdtype(array.dtype, np.floating):
            nan_count = np.isnan(array).sum()
            inf_count = np.isinf(array).sum()
            if nan_count > 0:
                print(f"  ⚠ NaN count: {nan_count}")
            if inf_count > 0:
                print(f"  ⚠ Inf count: {inf_count}")

    # Preview first few values for small arrays
    if array.size <= 10:
        print(f"  Values: {array.flatten()}")


def main():
    parser = argparse.ArgumentParser(
        description="Inspect reference data .npz files"
    )
    parser.add_argument(
        "npz_file",
        type=str,
        help="Path to .npz file"
    )
    parser.add_argument(
        "--array",
        type=str,
        default=None,
        help="Inspect only specific array (default: all)"
    )

    args = parser.parse_args()

    npz_path = Path(args.npz_file)

    if not npz_path.exists():
        print(f"Error: File not found: {npz_path}")
        return 1

    print(f"Inspecting: {npz_path}")
    print(f"File size: {format_size(npz_path.stat().st_size)}")

    # Load all arrays
    data = np.load(npz_path)

    print(f"\nArrays: {len(data.files)}")

    if args.array:
        # Inspect specific array
        if args.array not in data.files:
            print(f"Error: Array '{args.array}' not found")
            print(f"Available arrays: {', '.join(sorted(data.files))}")
            return 1

        inspect_array(args.array, data[args.array])
    else:
        # Inspect all arrays in sorted order
        for name in sorted(data.files):
            inspect_array(name, data[name])

    # Summary
    total_bytes = sum(data[name].nbytes for name in data.files)
    print(f"\n{'='*80}")
    print(f"Total arrays: {len(data.files)}")
    print(f"Total uncompressed size: {format_size(total_bytes)}")
    print('='*80)

    return 0


if __name__ == "__main__":
    exit(main())
